# development:
#   :address: smtp.gmail.com
#   :port: 587
#   :authentication: plain
#   :user_name: Rails.application.secrets.GMAIL_USERNAME
#   :password: Rails.application.secrets.GMAIL_PASSWORD
#   :enable_starttls_auto: true
# production:
#   :address: smtp.gmail.com
#   :port: 587
#   :authentication: plain
#   :user_name: ENV['GMAIL_USERNAME']
#   :password: ENV['GMAIL_PASSWORD']
#   :enable_starttls_auto: true
